name: ci-checks

on:
  workflow_call:

jobs:
  install-job:
    name: Install dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile

  typecheck-job:
    name: Typecheck
    needs: install-job
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck

  lint-job:
    name: Lint
    needs: install-job
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

  build-job:
    name: Build
    needs: install-job
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
